#!/usr/bin/env bash

## Setup new user in WSL (export username!)
sudo dnf install upgrade -y
dnf install passwd -y
dnf install util-linux-user -y
dnf install cracklib-dicts -y

useradd -m $username
sudo usermod -aG wheel $username
passwd $username

## su - $username

## Install ansible and git
sudo dnf install ansible -y
sudo dnf install git -y

## pull ansible config
git clone https://github.com/ncarchar/.ansible.git

## run playbook
ansible-playbook local.yml -K --ask-vault-pass
