- name: Ensure /.scrot directory exists
  file:
      path: "{{ lookup('env', 'HOME') }}/.scrot"
      state: directory
      mode: "0755"
  tags:
      - install
      - gui
- name: Install GUI packages
  become: true
  dnf:
    name:
      - alacritty
      - dmenu
      - redshift
      - feh
      - papirus-icon-theme
      - scrot
    state: present
  tags:
    - install
    - gui
