- name: Cloning .covfiles
  ansible.builtin.git:
      repo: "git@gitlab.ssh.covestro.com:carson.miller/covfiles.git"
      dest: "{{ lookup('env', 'HOME') }}/.covfiles"
      recursive: yes
      update: yes
      accept_hostkey: yes
      version: main
  tags:
      - covfiles

- name: Backup bash_profile
  ansible.builtin.shell:
    cmd: mv ~/.bash_profile ~/.bash_profile_bu

- name: Stow covfiles
  shell: cd $HOME/.covfiles && ./stow-work
  tags:
      - covfiles

- name: Remove bash_profile backup
  ansible.builtin.shell:
    cmd: rm ~/.bash_profile_bu
  tags:
      - covfiles

- name: Mirror to Windows
  become: true
  shell: cd {{ user_home + '/.covfiles' }} && './mirror-to-windows'
  tags:
      - mirror
      - covfiles
