- name: Cloning .dotfiles
  ansible.builtin.git:
      repo: "git@github.com:ncarchar/.dotfiles.git"
      dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
      recursive: yes
      update: yes
      accept_hostkey: yes
      version: main
  tags:
      - dotfiles
- name: Backup bashrc
  ansible.builtin.shell:
    cmd: mv ~/.bashrc ~/.bashrc_bu
- name: Stow dotfiles personal
  shell: cd $HOME/.dotfiles && ./stow-personal
  tags:
      - dotfiles
- name: Stow dotfiles work
  shell: cd $HOME/.dotfiles && ./stow-work
  tags:
      - dotfiles
- name: Remove bashrc backup
  ansible.builtin.shell:
    cmd: rm ~/.bashrc_bu
