- name: Set Git config universal
  git_config:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      scope: global
  loop:
      - { name: "init.defaultBranch", value: "main" }
      - {
            name: "filter.pom-remove-password.clean",
            value: "sed 's|<password>.*</password>|<password>***FILTERED***</password>|'",
        }
      - { name: "core.excludesFile", value: "~/.gitignore" }
  tags:
      - git-personal
      - git-work

- name: Ensure global .gitignore exists
  file:
    path: "~/.gitignore"
    state: touch
  tags:
    - git-personal
    - git-work

- name: Add patterns to global .gitignore
  lineinfile:
    path: "~/.gitignore"
    line: "{{ item }}"
    create: no
  loop:
    - "_task.md"
    - "target/"
    - "dist/"
  tags:
    - git-personal
    - git-work

- name: Set Git config personal
  git_config:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      scope: global
  loop:
      - { name: "user.name", value: "ncarchar" }
      - { name: "user.email", value: "carsoncmiller@proton.me" }
  when: is_personal
  tags:
      - git-personal

- name: Set Git config work
  git_config:
      name: "{{ item.name }}"
      value: "{{ item.value }}"
      scope: global
  loop:
      - { name: "user.email", value: "carson.miller@covestro.com" }
      - { name: "user.name", value: "Carson Miller" }
  when: is_work
  tags:
      - git-work
